// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idm.proto

package com.fitness.idm.proto;

public final class Idm {
  private Idm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fitness_idm_proto_UserGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fitness_idm_proto_UserGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fitness_idm_proto_TokenValidateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fitness_idm_proto_TokenValidateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fitness_idm_proto_TokenValidateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fitness_idm_proto_TokenValidateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fitness_idm_proto_CredentialsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fitness_idm_proto_CredentialsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fitness_idm_proto_EmptyGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fitness_idm_proto_EmptyGrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tidm.proto\022\025com.fitness.idm.proto\"H\n\010Us" +
      "erGrpc\022\n\n\002id\030\001 \001(\003\022\014\n\004role\030\002 \001(\t\022\020\n\010user" +
      "name\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\"%\n\024TokenVal" +
      "idateRequest\022\r\n\005token\030\001 \001(\t\"1\n\025TokenVali" +
      "dateResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004role\030\002 \001(\t\"8" +
      "\n\022CredentialsRequest\022\020\n\010username\030\001 \001(\t\022\020" +
      "\n\010password\030\002 \001(\t\"\023\n\021EmptyGrpcResponse2]\n" +
      "\013UserService\022N\n\ncreateUser\022\037.com.fitness" +
      ".idm.proto.UserGrpc\032\037.com.fitness.idm.pr" +
      "oto.UserGrpc2\274\002\n\014TokenService\022j\n\rvalidat",
      "eToken\022+.com.fitness.idm.proto.TokenVali" +
      "dateRequest\032,.com.fitness.idm.proto.Toke" +
      "nValidateResponse\022_\n\005login\022).com.fitness" +
      ".idm.proto.CredentialsRequest\032+.com.fitn" +
      "ess.idm.proto.TokenValidateRequest\022_\n\006lo" +
      "gout\022+.com.fitness.idm.proto.TokenValida" +
      "teRequest\032(.com.fitness.idm.proto.EmptyG" +
      "rpcResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fitness_idm_proto_UserGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fitness_idm_proto_UserGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fitness_idm_proto_UserGrpc_descriptor,
        new String[] { "Id", "Role", "Username", "Password", });
    internal_static_com_fitness_idm_proto_TokenValidateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fitness_idm_proto_TokenValidateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fitness_idm_proto_TokenValidateRequest_descriptor,
        new String[] { "Token", });
    internal_static_com_fitness_idm_proto_TokenValidateResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_fitness_idm_proto_TokenValidateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fitness_idm_proto_TokenValidateResponse_descriptor,
        new String[] { "Id", "Role", });
    internal_static_com_fitness_idm_proto_CredentialsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_fitness_idm_proto_CredentialsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fitness_idm_proto_CredentialsRequest_descriptor,
        new String[] { "Username", "Password", });
    internal_static_com_fitness_idm_proto_EmptyGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_fitness_idm_proto_EmptyGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fitness_idm_proto_EmptyGrpcResponse_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
