// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idm.proto

package com.fitness.idm.proto;

public interface TokenValidateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fitness.idm.proto.TokenValidateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
