// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idm.proto

package com.fitness.idm.proto;

public interface UserGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fitness.idm.proto.UserGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string role = 2;</code>
   */
  String getRole();
  /**
   * <code>string role = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string username = 3;</code>
   */
  String getUsername();
  /**
   * <code>string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 4;</code>
   */
  String getPassword();
  /**
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
