// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idm.proto

package com.fitness.gateway.proto;

public interface EmptyGrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fitness.idm.proto.EmptyGrpcResponse)
    com.google.protobuf.MessageOrBuilder {
}
