// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idm.proto

package com.fitness.idm.proto;

public interface TokenValidateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fitness.idm.proto.TokenValidateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string role = 2;</code>
   */
  String getRole();
  /**
   * <code>string role = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
